# Generated by Django 4.0.4 on 2022-05-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desciption',
            new_name='description',
        ),
    ]
