# Generated by Django 4.0.4 on 2022-06-10 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_desciption_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('computers', 'computers'), ('science', 'science'), ('technology', 'technology'), ('math', 'math')], default='computers', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
