# Generated by Django 4.0.4 on 2022-06-10 14:35

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_category_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, validators=[articles.validators.min_len_validator]),
        ),
    ]
