# Generated by Django 4.0.4 on 2022-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
