# Generated by Django 4.0.4 on 2022-07-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_date_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
